<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ShipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ships')->insert([
            [ 'name' => 'おふゆ' , 'ex_name' => '' , 'former_name' => 'くまの丸' , 'yard' => '金川' , 'ship_no' => '548' , 'yard' => '金川' , 'ship_no' => '548' , 'delivered' => '2006-01-01' , 'gross_tonn' => '194' , 'operat_section_id' => '4' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'そうや' , 'ex_name' => '' , 'former_name' => 'あきつ丸' , 'yard' => '金川' , 'ship_no' => '603' , 'yard' => '金川' , 'ship_no' => '603' , 'delivered' => '2009-11-01' , 'gross_tonn' => '194' , 'operat_section_id' => '4' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'まみや' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '686' , 'yard' => '金川' , 'ship_no' => '686' , 'delivered' => '2016-05-01' , 'gross_tonn' => '192' , 'operat_section_id' => '5' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'つがる' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '750' , 'yard' => '金川' , 'ship_no' => '750' , 'delivered' => '2020-04-01' , 'gross_tonn' => '194' , 'operat_section_id' => '5' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => '北野丸' , 'ex_name' => '' , 'former_name' => '北野丸' , 'yard' => '金川' , 'ship_no' => '378' , 'yard' => '金川' , 'ship_no' => '378' , 'delivered' => '1992-09-01' , 'gross_tonn' => '196' , 'operat_section_id' => '6' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'らいちょう' , 'ex_name' => '' , 'former_name' => 'たまの丸' , 'yard' => '金川' , 'ship_no' => '511' , 'yard' => '金川' , 'ship_no' => '511' , 'delivered' => '2002-11-01' , 'gross_tonn' => '193' , 'operat_section_id' => '7' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => '三保丸' , 'ex_name' => '' , 'former_name' => 'あわじ丸' , 'yard' => '金川' , 'ship_no' => '619' , 'yard' => '金川' , 'ship_no' => '619' , 'delivered ' => '2010-11-01' , 'gross_tonn' => '196' , 'operat_section_id' => '7' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'きよす' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '762' , 'yard' => '金川' , 'ship_no' => '762' , 'delivered' => '2021-08-01' , 'gross_tonn' => '198' , 'operat_section_id' => '2' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'かりや丸' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '707' , 'yard' => '金川' , 'ship_no' => '707' , 'delivered' => '2018-04-01' , 'gross_tonn' => '197' , 'operat_section_id' => '2' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'あけの丸' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '690' , 'yard' => '金川' , 'ship_no' => '690' , 'delivered' => '2016-09-01' , 'gross_tonn' => '196' , 'operat_section_id' => '2' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'あつみ丸' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '659' , 'yard' => '金川' , 'ship_no' => '659' , 'delivered' => '2014-02-01' , 'gross_tonn' => '195' , 'operat_section_id' => '2' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'くまの' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '772' , 'yard' => '金川' , 'ship_no' => '772' , 'delivered' => '2023-03-01' , 'gross_tonn' => '198' , 'operat_section_id' => '2' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'つしま丸' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '752' , 'yard' => '金川' , 'ship_no' => '752' , 'delivered' => '2020-06-01' , 'gross_tonn' => '196' , 'operat_section_id' => '2' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'とらいとん' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '580' , 'yard' => '金川' , 'ship_no' => '580' , 'delivered' => '2008-07-01' , 'gross_tonn' => '209' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'いしん' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '720' , 'yard' => '金川' , 'ship_no' => '720' , 'delivered' => '2019-02-01' , 'gross_tonn' => '247' , 'operat_section_id' => '1' , 'navigation_area_id' => '3' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'あさか丸' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '645' , 'yard' => '金川' , 'ship_no' => '645' , 'delivered' => '2012-09-01' , 'gross_tonn' => '233' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => '布引丸' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '629' , 'yard' => '金川' , 'ship_no' => '629' , 'delivered' => '2012-08-01' , 'gross_tonn' => '208' , 'operat_section_id' => '3' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => '港島丸' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '680' , 'yard' => '金川' , 'ship_no' => '680' , 'delivered' => '2016-02-01' , 'gross_tonn' => '194' , 'operat_section_id' => '3' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'シリウス' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '569' , 'yard' => '金川' , 'ship_no' => '569' , 'delivered' => '2007-11-01' , 'gross_tonn' => '117' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'ぎんが' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '358' , 'yard' => '金川' , 'ship_no' => '358' , 'delivered' => '2003-09-01' , 'gross_tonn' => '78' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'みやま' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '660' , 'yard' => '金川' , 'ship_no' => '660' , 'delivered' => '2014-05-01' , 'gross_tonn' => '235' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'たまの' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '698' , 'yard' => '金川' , 'ship_no' => '698' , 'delivered' => '2017-10-01' , 'gross_tonn' => '198' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'こつぢ丸' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '670' , 'yard' => '金川' , 'ship_no' => '670' , 'delivered' => '2015-02-01' , 'gross_tonn' => '205' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'かさど丸' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '525' , 'yard' => '金川' , 'ship_no' => '525' , 'delivered' => '2004-03-01' , 'gross_tonn' => '209' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'こまち丸' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '612' , 'yard' => '金川' , 'ship_no' => '612' , 'delivered' => '2011-07-01' , 'gross_tonn' => '205' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'かいた丸' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '713' , 'yard' => '金川' , 'ship_no' => '713' , 'delivered' => '2018-06-01' , 'gross_tonn' => '196' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'おおつ丸' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '677' , 'yard' => '金川' , 'ship_no' => '677' , 'delivered' => '2015-07-01' , 'gross_tonn' => '196' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => '長門' , 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '631' , 'yard' => '金川' , 'ship_no' => '631' , 'delivered' => '2011-09-01' , 'gross_tonn' => '193' , 'operat_section_id' => '9' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'あすか' , 'ex_name' => 'みほ丸' , 'former_name' => 'あかし丸' , 'yard' => '金川' , 'ship_no' => '483' , 'yard' => '金川' , 'ship_no' => '483' , 'delivered' => '2000-04-01' , 'gross_tonn' => '195' , 'operat_section_id' => '8' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => '飛鳥丸' , 'ex_name' => '' , 'former_name' => '赤城丸' , 'yard' => '金川' , 'ship_no' => '361' , 'yard' => '金川' , 'ship_no' => '361' , 'delivered' => '1991-07-01' , 'gross_tonn' => '196' , 'operat_section_id' => '8' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'てくのすⅡ' , 'ex_name' => '' , 'former_name' => '' , 'yard' => 'ダイゾー' , 'ship_no' => '514' , 'yard' => 'ダイゾー' , 'ship_no' => '514' , 'delivered' => '2017-03-01' , 'gross_tonn' => '186' , 'operat_section_id' => '10' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
             ]); 
    }
}
