<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ShipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ships')->insert([
            [ 'name' => 'おふゆ' ,'issueInspCert'=>'2021-08-29', 'ex_name' => '' , 'former_name' => 'くまの丸' , 'yard' => '金川' , 'ship_no' => '548' , 'yard' => '金川' , 'ship_no' => '548' , 'delivered' => '2006-01-01' , 'gross_tonn' => '194' , 'operat_section_id' => '4' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'そうや' ,'issueInspCert'=>'2022-06-07', 'ex_name' => '' , 'former_name' => 'あきつ丸' , 'yard' => '金川' , 'ship_no' => '603' , 'yard' => '金川' , 'ship_no' => '603' , 'delivered' => '2009-11-01' , 'gross_tonn' => '194' , 'operat_section_id' => '4' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'まみや' ,'issueInspCert'=> null, 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '686' , 'yard' => '金川' , 'ship_no' => '686' , 'delivered' => '2016-05-01' , 'gross_tonn' => '192' , 'operat_section_id' => '5' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'つがる' ,'issueInspCert'=>'2020-04-13', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '750' , 'yard' => '金川' , 'ship_no' => '750' , 'delivered' => '2020-04-01' , 'gross_tonn' => '194' , 'operat_section_id' => '5' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => '北野丸' ,'issueInspCert'=> null, 'ex_name' => '' , 'former_name' => '北野丸' , 'yard' => '金川' , 'ship_no' => '378' , 'yard' => '金川' , 'ship_no' => '378' , 'delivered' => '1992-09-01' , 'gross_tonn' => '196' , 'operat_section_id' => '6' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'らいちょう' ,'issueInspCert'=>'2017-10-31', 'ex_name' => '' , 'former_name' => 'たまの丸' , 'yard' => '金川' , 'ship_no' => '511' , 'yard' => '金川' , 'ship_no' => '511' , 'delivered' => '2002-11-01' , 'gross_tonn' => '193' , 'operat_section_id' => '7' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => '三保丸' ,'issueInspCert'=>'2023-04-28', 'ex_name' => '' , 'former_name' => 'あわじ丸' , 'yard' => '金川' , 'ship_no' => '619' , 'yard' => '金川' , 'ship_no' => '619' , 'delivered ' => '2010-11-01' , 'gross_tonn' => '196' , 'operat_section_id' => '7' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'きよす' ,'issueInspCert'=>'2021-07-30', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '762' , 'yard' => '金川' , 'ship_no' => '762' , 'delivered' => '2021-08-01' , 'gross_tonn' => '198' , 'operat_section_id' => '2' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'かりや丸' ,'issueInspCert'=>'2018-04-16', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '707' , 'yard' => '金川' , 'ship_no' => '707' , 'delivered' => '2018-04-01' , 'gross_tonn' => '197' , 'operat_section_id' => '2' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'あけの丸' ,'issueInspCert'=>'2020-07-27', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '690' , 'yard' => '金川' , 'ship_no' => '690' , 'delivered' => '2016-09-01' , 'gross_tonn' => '196' , 'operat_section_id' => '2' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'あつみ丸' ,'issueInspCert'=>'2018-11-20', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '659' , 'yard' => '金川' , 'ship_no' => '659' , 'delivered' => '2014-02-01' , 'gross_tonn' => '195' , 'operat_section_id' => '2' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'くまの' ,'issueInspCert'=>'2023-03-16', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '772' , 'yard' => '金川' , 'ship_no' => '772' , 'delivered' => '2023-03-01' , 'gross_tonn' => '198' , 'operat_section_id' => '2' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'つしま丸' ,'issueInspCert'=>'2020-06-08', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '752' , 'yard' => '金川' , 'ship_no' => '752' , 'delivered' => '2020-06-01' , 'gross_tonn' => '196' , 'operat_section_id' => '2' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'とらいとん' ,'issueInspCert'=>'2023-05-19', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '580' , 'yard' => '金川' , 'ship_no' => '580' , 'delivered' => '2008-07-01' , 'gross_tonn' => '209' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'いしん' ,'issueInspCert'=>'2019-02-25', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '720' , 'yard' => '金川' , 'ship_no' => '720' , 'delivered' => '2019-02-01' , 'gross_tonn' => '247' , 'operat_section_id' => '1' , 'navigation_area_id' => '3' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'あさか丸' ,'issueInspCert'=>'2022-08-01', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '645' , 'yard' => '金川' , 'ship_no' => '645' , 'delivered' => '2012-09-01' , 'gross_tonn' => '233' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => '布引丸' ,'issueInspCert'=>'2018-07-31', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '629' , 'yard' => '金川' , 'ship_no' => '629' , 'delivered' => '2012-08-01' , 'gross_tonn' => '208' , 'operat_section_id' => '3' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => '港島丸' ,'issueInspCert'=>'2022-01-25', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '680' , 'yard' => '金川' , 'ship_no' => '680' , 'delivered' => '2016-02-01' , 'gross_tonn' => '194' , 'operat_section_id' => '3' , 'navigation_area_id' => '1' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'シリウス' ,'issueInspCert'=>'2022-11-08', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '569' , 'yard' => '金川' , 'ship_no' => '569' , 'delivered' => '2007-11-01' , 'gross_tonn' => '117' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'ぎんが' ,'issueInspCert'=>'2023-09-22', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '358' , 'yard' => '金川' , 'ship_no' => '358' , 'delivered' => '2003-09-01' , 'gross_tonn' => '78' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'みやま' ,'issueInspCert'=>'2019-04-25', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '660' , 'yard' => '金川' , 'ship_no' => '660' , 'delivered' => '2014-05-01' , 'gross_tonn' => '235' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'たまの' ,'issueInspCert'=>'2022-09-30', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '698' , 'yard' => '金川' , 'ship_no' => '698' , 'delivered' => '2017-10-01' , 'gross_tonn' => '198' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'こつぢ丸' ,'issueInspCert'=>'2019-11-25', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '670' , 'yard' => '金川' , 'ship_no' => '670' , 'delivered' => '2015-02-01' , 'gross_tonn' => '205' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'かさど丸' ,'issueInspCert'=>'2019-01-16', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '525' , 'yard' => '金川' , 'ship_no' => '525' , 'delivered' => '2004-03-01' , 'gross_tonn' => '209' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'こまち丸' ,'issueInspCert'=>'2021-05-19', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '612' , 'yard' => '金川' , 'ship_no' => '612' , 'delivered' => '2011-07-01' , 'gross_tonn' => '205' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'かいた丸' ,'issueInspCert'=>'2023-05-30', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '713' , 'yard' => '金川' , 'ship_no' => '713' , 'delivered' => '2018-06-01' , 'gross_tonn' => '196' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'おおつ丸' ,'issueInspCert'=>'2020-05-14', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '677' , 'yard' => '金川' , 'ship_no' => '677' , 'delivered' => '2015-07-01' , 'gross_tonn' => '196' , 'operat_section_id' => '1' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => '長門' ,'issueInspCert'=>'2021-09-09', 'ex_name' => '' , 'former_name' => '' , 'yard' => '金川' , 'ship_no' => '631' , 'yard' => '金川' , 'ship_no' => '631' , 'delivered' => '2011-09-01' , 'gross_tonn' => '193' , 'operat_section_id' => '9' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'あすか' ,'issueInspCert'=> null, 'ex_name' => 'みほ丸' , 'former_name' => 'あかし丸' , 'yard' => '金川' , 'ship_no' => '483' , 'yard' => '金川' , 'ship_no' => '483' , 'delivered' => '2000-04-01' , 'gross_tonn' => '195' , 'operat_section_id' => '8' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => '飛鳥丸' ,'issueInspCert'=> null, 'ex_name' => '' , 'former_name' => '赤城丸' , 'yard' => '金川' , 'ship_no' => '361' , 'yard' => '金川' , 'ship_no' => '361' , 'delivered' => '1991-07-01' , 'gross_tonn' => '196' , 'operat_section_id' => '8' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
            [ 'name' => 'てくのすⅡ' ,'issueInspCert'=>'2021-03-02', 'ex_name' => '' , 'former_name' => '' , 'yard' => 'ダイゾー' , 'ship_no' => '514' , 'yard' => 'ダイゾー' , 'ship_no' => '514' , 'delivered' => '2017-03-01' , 'gross_tonn' => '186' , 'operat_section_id' => '10' , 'navigation_area_id' => '2' , 'created_at' => '2023-08-01' ] ,																																																																						
             ]); 
    }
}
